### PR TITLE
Issue #9, #51: Fix invalid output diff in Windows CMD due to CR in output

### LINKED ISSUE #51: Can't run in Vim and problem in Window CMD.
**Information:**
cpbooster version: run `cpb -v` to get this information
OS: Windows
Using Vim : yes (gVim but can run in gVim I have to run it in terminal) 
Terminal Name: CMD

**Describe the bug**
Not print the all answer when it wrong
And can't Test, Debug, ... on Vim or gVim

**Steps To Reproduce it**
1. Run wrong code in terminal, or run by command :Test on gVim  
2. Only print the last test case, or can't run by commmand

**Screenshots**
Screenshot 2022-04-09 000322
Screenshot 2022-04-03 201953

### PR DESCRIPTION
**Pull request by MohamedIrfanAM**
Resolves #51 #9

### CODE REVIEW

**Comment by searleser97** [comment]
The issue with using trimmed lines is that it also removes spaces at the end or begining, so if someone added some spaces accidentally it will no longer be detected by cpbooster, however, from the code change looks like the issue is just the line ending so probably we could just normalize the line endings depending on the OS

**Comment by MohamedIrfanAM** [comment]
In windows compiled output has '\r\n' instead of '\n' at end of each line. This creates two problems
1.  `Veredict.AC_WHEN_TRIMMED` is found instead of `Veredict.AC` because `output` and `ans` will never be same https://github.com/searleser97/cpbooster/blob/cdfbd6fe91dcde76c101922718542002f934689c/app/src/Test/TesterFactory/Tester.ts#L204C3-L204C3
2. https://github.com/searleser97/cpbooster/blob/cdfbd6fe91dcde76c101922718542002f934689c/app/src/Test/TesterFactory/Tester.ts#L187
when this `.split("\n")` is called the `outputLines` is left with `"\r"` at end of each line and this creates weird output

Both problems can be fixed if we replace all` '\r\n'` sequence in the output file with `'\n'`
Something like 
```
    const isWindows = os.type() === "Windows_NT" || os.release().includes("Microsoft");
    let output = execution.stdout?.toString() ?? "";
    const ans = fs.readFileSync(answerFilePath).toString();
    if(isWindows){
      output = output.replace(/\r\n/g, "\n");
    }
```

**Comment by searleser97** [comment]
> In windows compiled output has '\r\n' instead of '\n' at end of each line. This creates two problems
> 
> 1. `Veredict.AC_WHEN_TRIMMED` is found instead of `Veredict.AC` because `output` and `ans` will never be same https://github.com/searleser97/cpbooster/blob/cdfbd6fe91dcde76c101922718542002f934689c/app/src/Test/TesterFactory/Tester.ts#L204C3-L204C3
> 2. https://github.com/searleser97/cpbooster/blob/cdfbd6fe91dcde76c101922718542002f934689c/app/src/Test/TesterFactory/Tester.ts#L187
>    
>    when this `.split("\n")` is called the `outputLines` is left with `"\r"` at end of each line and this creates weird output
> 
> Both problems can be fixed if we replace all` '\r\n'` sequence in the output file with `'\n'` Something like
> 
> ```
>     const isWindows = os.type() === "Windows_NT" || os.release().includes("Microsoft");
>     let output = execution.stdout?.toString() ?? "";
>     const ans = fs.readFileSync(answerFilePath).toString();
>     if(isWindows){
>       output = output.replace(/\r\n/g, "\n");
>     }
> ```
> 
> May I proceed?

I agree, let's do that

**Comment by MohamedIrfanAM** [comment]
I moved isWindows to Util, is that okay? https://github.com/searleser97/cpbooster/pull/98/commits/fe0b510ee72385d22218e3234a903330cd4bd9a6

**Comment by MohamedIrfanAM** [comment]
Is there any way you could apply `hacktoberfest-accepted` label to my PR. I am trying to complete hacktober fest challenge.

**Pull request merged**
